import { render, screen, waitFor, fireEvent } from "@testing-library/react";
import AdministrationPage from "./AdministrationPage";
import api from "../services/api";
let mockLocation = { search: "?section=ai-dubbing" };
jest.mock("react-router-dom", () => ({ useLocation: () => mockLocation }), { virtual: true });
jest.mock("../services/api", () => ({ __esModule: true, default: { get: jest.fn(), post: jest.fn() } }));
jest.mock("./FormNewAdmin", () => () => <section><h2>FormNewAdmin</h2><input aria-label="FormNewAdmin" /></section>);
jest.mock("./AdminList", () => () => <section><h2>AdminList</h2><input aria-label="AdminList" /></section>);
jest.mock("./UserManagerCard", () => () => <section><h2>UserManagerCard</h2><input aria-label="UserManagerCard" /></section>);
jest.mock("./AdminMessageSettings", () => () => <section><h2>AdminMessageSettings</h2><input aria-label="AdminMessageSettings" /></section>);
jest.mock("./AdminGenreManager", () => () => <section><h2>AdminGenreManager</h2><input aria-label="AdminGenreManager" /></section>);
jest.mock("./AdminHomepageGenreManager", () => () => <section><h2>AdminHomepageGenreManager</h2><input aria-label="AdminHomepageGenreManager" /></section>);
jest.mock("./AdminFavoriteContentManager", () => () => <section><h2>AdminFavoriteContentManager</h2><input aria-label="AdminFavoriteContentManager" /></section>);
jest.mock("./AdminSeriesManager", () => () => <section><h2>AdminSeriesManager</h2><input aria-label="AdminSeriesManager" /></section>);
jest.mock("./AdminSagaManager", () => () => <section><h2>AdminSagaManager</h2><input aria-label="AdminSagaManager" /></section>);
jest.mock("./AdminUniverseManager", () => () => <section><h2>AdminUniverseManager</h2><input aria-label="AdminUniverseManager" /></section>);
jest.mock("./AdminVideoManager", () => () => <section><h2>AdminVideoManager</h2><input aria-label="AdminVideoManager" /></section>);
jest.mock("./AdminMusicContentManager", () => () => <section><h2>AdminMusicContentManager</h2><input aria-label="AdminMusicContentManager" /></section>);
jest.mock("./AdminPersonManager", () => () => <section><h2>AdminPersonManager</h2><input aria-label="AdminPersonManager" /></section>);
jest.mock("./SuperAdminVideoTrashManager", () => () => <section><h2>SuperAdminVideoTrashManager</h2><input aria-label="SuperAdminVideoTrashManager" /></section>);
jest.mock("./SuperAdminSagaTrashManager", () => () => <section><h2>SuperAdminSagaTrashManager</h2><input aria-label="SuperAdminSagaTrashManager" /></section>);
jest.mock("./SuperAdminUniverseTrashManager", () => () => <section><h2>SuperAdminUniverseTrashManager</h2><input aria-label="SuperAdminUniverseTrashManager" /></section>);
jest.mock("./SuperAdminMusicTrashManager", () => () => <section><h2>SuperAdminMusicTrashManager</h2><input aria-label="SuperAdminMusicTrashManager" /></section>);
jest.mock("./SuperAdminPersonTrashManager", () => () => <section><h2>SuperAdminPersonTrashManager</h2><input aria-label="SuperAdminPersonTrashManager" /></section>);
jest.mock("./AdminBackupManager", () => () => <section><h2>AdminBackupManager</h2><input aria-label="AdminBackupManager" /></section>);
jest.mock("./AdminExperimentalFeatures", () => () => <section><h2>AdminExperimentalFeatures</h2><input aria-label="AdminExperimentalFeatures" /></section>);
jest.mock("./AdminDistributedEncodingDiagnostics", () => () => <section><h2>AdminDistributedEncodingDiagnostics</h2><input aria-label="AdminDistributedEncodingDiagnostics" /></section>);
jest.mock("./AdminAiSubtitleManager", () => () => <section><h2>AdminAiSubtitleManager</h2><input aria-label="AdminAiSubtitleManager" /></section>);
jest.mock("./AdminAiSubtitleLibraryManager", () => () => <section><h2>AdminAiSubtitleLibraryManager</h2><input aria-label="AdminAiSubtitleLibraryManager" /></section>);
jest.mock("./AdminAiDubbingManager", () => () => <section><h2>AdminAiDubbingManager</h2><input aria-label="AdminAiDubbingManager" /></section>);
jest.mock("./SuperAdminAiSubtitleEditor", () => () => <section><h2>SuperAdminAiSubtitleEditor</h2><input aria-label="SuperAdminAiSubtitleEditor" /></section>);
beforeEach(() => { jest.clearAllMocks(); mockLocation = { search: "?section=ai-dubbing" }; api.get.mockResolvedValue({ data: { GradeID: 1 } }); });
it("affiche uniquement la section choisie sans suraccordéon et conserve la saisie lors du retour", async () => {
 const { rerender } = render(<AdministrationPage />);
 const input = await screen.findByRole("textbox", { name: "AdminAiDubbingManager" });
 fireEvent.change(input, { target: { value: "en cours" } });
 expect(screen.queryByText("AdminMessageSettings")).not.toBeInTheDocument();
 expect(screen.queryByRole("button", { name: "Doublages audio IA" })).not.toBeInTheDocument();
 mockLocation = { search: "?section=message" }; rerender(<AdministrationPage />);
 expect(await screen.findByText("AdminMessageSettings")).toBeVisible();
 expect(input).not.toBeVisible();
 mockLocation = { search: "?section=ai-dubbing" }; rerender(<AdministrationPage />);
 expect(screen.getByRole("textbox", { name: "AdminAiDubbingManager" })).toHaveValue("en cours");
});
it("un admin ne monte pas une section réservée au superadmin via URL directe", async () => {
 api.get.mockResolvedValue({ data: { GradeID: 2 } }); mockLocation = { search: "?section=backups" };
 render(<AdministrationPage />);
 await screen.findByRole("heading", { name: "Administration" });
 expect(screen.queryByText("AdminBackupManager")).not.toBeInTheDocument();
 expect(screen.getByRole("heading", { name: "Contenus à la une" })).toBeVisible();
});
it("refuse un utilisateur ordinaire sans monter les outils", async () => {
 api.get.mockResolvedValue({ data: { GradeID: 3 } }); render(<AdministrationPage />);
 await waitFor(() => expect(screen.getByRole("alert")).toHaveTextContent("Accès réservé"));
 expect(screen.queryByText("AdminAiDubbingManager")).not.toBeInTheDocument();
});
