export const DISTRIBUTED_ENCODING_PROTOCOL_VERSION = 1;
export const DISTRIBUTED_ENCODING_PIPELINE_VERSION =
  "sami-hls-libx264-aac-v1";

export const DISTRIBUTED_ENCODING_HEARTBEAT_INTERVAL_MS = 15 * 1000;
export const DISTRIBUTED_ENCODING_OFFLINE_AFTER_MS = 45 * 1000;
export const DISTRIBUTED_ENCODING_LEASE_DURATION_MS = 120 * 1000;
export const DISTRIBUTED_ENCODING_LEASE_RENEW_INTERVAL_MS = 30 * 1000;
export const DISTRIBUTED_ENCODING_PRIMARY_FALLBACK_AFTER_MS = 5 * 60 * 1000;
export const DISTRIBUTED_ENCODING_PRIMARY_MAX_NOMINAL_HEIGHT = 360;
export const DISTRIBUTED_ENCODING_MAX_SLOTS = 1;
export const DISTRIBUTED_ENCODING_CACHE_MAX_BYTES = 50 * 1024 * 1024 * 1024;
export const DISTRIBUTED_ENCODING_FAILED_CACHE_TTL_MS = 24 * 60 * 60 * 1000;
export const DISTRIBUTED_ENCODING_FAILURE_CACHE_TTL_MS =
  DISTRIBUTED_ENCODING_FAILED_CACHE_TTL_MS;
// Une planification normale ne dure que quelques secondes après le probe. Le
// délai laisse néanmoins une marge confortable aux extractions de sous-titres
// et aux écritures lentes avant de considérer le job comme interrompu.
export const DISTRIBUTED_ENCODING_PLANNING_TIMEOUT_MS = 30 * 60 * 1000;
// Une ingestion peut transférer jusqu'à 50 Gio : elle bénéficie du même délai
// prudent que les workspaces sans ligne DB avant d'être déclarée abandonnée.
export const DISTRIBUTED_ENCODING_INGESTING_TIMEOUT_MS = 24 * 60 * 60 * 1000;
export const DISTRIBUTED_ENCODING_ORPHAN_WORKSPACE_TTL_MS = 24 * 60 * 60 * 1000;
export const INCOMPLETE_ENCODING_CLEANUP_STEP = "incomplete_cleanup_pending";
export const INCOMPLETE_ENCODING_EXPIRED_STEP = "incomplete_expired";
export const DISTRIBUTED_ENCODING_RETRY_BACKOFF_MS = Object.freeze([
  15 * 1000,
  60 * 1000,
  5 * 60 * 1000,
]);

export const ENCODING_WORKER_ROLE = Object.freeze({
  PRIMARY: "PRIMARY",
  CLONE: "CLONE",
});

export const ENCODING_JOB_STATUS = Object.freeze({
  INGESTING: "INGESTING",
  PLANNING: "PLANNING",
  QUEUED: "QUEUED",
  RUNNING: "RUNNING",
  ASSEMBLING: "ASSEMBLING",
  VERIFYING: "VERIFYING",
  PUBLISHING: "PUBLISHING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  CANCEL_REQUESTED: "CANCEL_REQUESTED",
  CANCELLED: "CANCELLED",
});

export const ENCODING_TASK_KIND = Object.freeze({
  VIDEO_PROFILE: "VIDEO_PROFILE",
  AUDIO_RENDITION: "AUDIO_RENDITION",
});

export const ENCODING_TASK_STATUS = Object.freeze({
  PENDING: "PENDING",
  LEASED: "LEASED",
  RETRY_WAIT: "RETRY_WAIT",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
});

export const ENCODING_TASK_PHASE = Object.freeze({
  DOWNLOADING: "DOWNLOADING",
  ENCODING: "ENCODING",
  UPLOADING: "UPLOADING",
  VERIFYING: "VERIFYING",
});

export const ENCODING_ATTEMPT_STATUS = Object.freeze({
  RUNNING: "RUNNING",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
});

export const ENCODING_ARTIFACT_STATUS = Object.freeze({
  PENDING: "PENDING",
  UPLOADING: "UPLOADING",
  VERIFIED: "VERIFIED",
  FAILED: "FAILED",
});

export const ACTIVE_ENCODING_JOB_STATUSES = Object.freeze([
  ENCODING_JOB_STATUS.INGESTING,
  ENCODING_JOB_STATUS.PLANNING,
  ENCODING_JOB_STATUS.QUEUED,
  ENCODING_JOB_STATUS.RUNNING,
  ENCODING_JOB_STATUS.ASSEMBLING,
  ENCODING_JOB_STATUS.VERIFYING,
  ENCODING_JOB_STATUS.PUBLISHING,
  ENCODING_JOB_STATUS.CANCEL_REQUESTED,
]);

export const CLAIMABLE_ENCODING_TASK_STATUSES = Object.freeze([
  ENCODING_TASK_STATUS.PENDING,
  ENCODING_TASK_STATUS.RETRY_WAIT,
]);

export const TERMINAL_ENCODING_TASK_STATUSES = new Set([
  ENCODING_TASK_STATUS.SUCCEEDED,
  ENCODING_TASK_STATUS.FAILED,
  ENCODING_TASK_STATUS.CANCELLED,
]);
