export const AI_DUBBING_LANGUAGES = Object.freeze([
  { code: "en", label: "Anglais" },
  { code: "fr", label: "Français" },
  { code: "ja", label: "Japonais" },
]);

export const AI_DUBBING_SIGNATURE_DOMAIN = "SAMI-AI-DUBBING-V1";
export const AI_DUBBING_PROTOCOL_VERSION = 1;
export const AI_DUBBING_PIPELINE_VERSION = "sami-dubbing-v6-clean-phrases-r9-r1";
export const AI_DUBBING_OFFLINE_AFTER_MS = 45_000;
export const AI_DUBBING_HEARTBEAT_INTERVAL_MS = 15_000;
export const AI_DUBBING_LEASE_DURATION_MS = 2 * 60 * 1000;
export const AI_DUBBING_LEASE_RENEW_INTERVAL_MS = 30_000;
export const AI_DUBBING_CLAIM_INTERVAL_MS = 10_000;
export const AI_DUBBING_WORKER_FAILURE_COOLDOWN_MS = 5 * 60 * 1000;
export const AI_DUBBING_RETRY_BACKOFF_MS = Object.freeze([
  60_000,
  5 * 60_000,
  30 * 60_000,
  2 * 60 * 60_000,
]);

export const AI_DUBBING_STATUS = Object.freeze({
  QUEUED_PREVIEW: "QUEUED_PREVIEW",
  PROCESSING_PREVIEW: "PROCESSING_PREVIEW",
  PREVIEW_REVIEW: "PREVIEW_REVIEW",
  QUEUED_FULL: "QUEUED_FULL",
  PROCESSING_FULL: "PROCESSING_FULL",
  FINAL_REVIEW: "FINAL_REVIEW",
  PUBLISHED: "PUBLISHED",
  REJECTED: "REJECTED",
  FAILED: "FAILED",
});

export const ACTIVE_AI_DUBBING_STATUSES = Object.freeze([
  AI_DUBBING_STATUS.QUEUED_PREVIEW,
  AI_DUBBING_STATUS.PROCESSING_PREVIEW,
  AI_DUBBING_STATUS.PREVIEW_REVIEW,
  AI_DUBBING_STATUS.QUEUED_FULL,
  AI_DUBBING_STATUS.PROCESSING_FULL,
  AI_DUBBING_STATUS.FINAL_REVIEW,
]);

export const AI_DUBBING_PROCESSING_STATUSES = Object.freeze([
  AI_DUBBING_STATUS.PROCESSING_PREVIEW,
  AI_DUBBING_STATUS.PROCESSING_FULL,
]);
